version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./app:/app/app:cached
      - ./scripts:/app/scripts:cached
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:cached
      - ./out:/app/out
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql+asyncpg://enginemaker:password@db:5432/shareengine
      - JWT_SECRET_KEY=CompaniesOverCountries
      - HASH_ALGORITHM=HS256
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - ./app/db/local/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: enginemaker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shareengine
    ports:
      - 5433:5432

volumes:
  postgres_data:
