import { ItemProps } from "./components/Item";

export const dummyItems: ItemProps[] = [
    {
        name: "iPhone 12 Pro",
        status: true,
        price: 1000,
        id: "1",
        photos: ["https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-pro-family-hero?wid=940&hei=1112&fmt=jpeg&qlt=80&.v=1604021662000", "https://cdn.mos.cms.futurecdn.net/r3GihyTvkBBbiG3wTTsP99-1200-80.jpg.webp"],
        // image_url1: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-pro-family-hero?wid=940&hei=1112&fmt=jpeg&qlt=80&.v=1604021662000",
        owner: "John Doe",
        description: "A high-end smartphone with advanced features. ここに説明文がはいります。ここに説明文がはいります。ここに説明文がはいります。ここに説明文がはいります。ここに説明文がはいります。ここに説明文がはいります。",
        precaution: "Handle with care. ここに注意事項がはいります。ここに注意事項が入ります。ここに注意事項がはいります。ここに注意事項が入ります。ここに注意事項がはいります。ここに注意事項が入ります。",
        days: 7,
    },
    {
        name: "MacBook Pro",
        status: true,
        price: 0,
        id: "2",
        photos: ["https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-spacegray-select-202011?wid=892&hei=820&fmt=jpeg&qlt=80&.v=1603406905000"],
        owner: "Jane Smith",
        description: "A powerful laptop for professional use.",
        precaution: "Do not spill water on it.",
        days: 14,
    },
    {
        name: "Nintendo Switch",
        status: false,
        price: 300,
        id: "i9j0k1l2",
        photos: ["https://media.istockphoto.com/id/801931948/ja/%E3%82%B9%E3%83%88%E3%83%83%E3%82%AF%E3%83%95%E3%82%A9%E3%83%88/%E3%83%90%E3%83%B3%E3%82%B3%E3%82%AF-%E3%82%BF%E3%82%A4%E7%8E%8B%E5%9B%BD-2017-%E5%B9%B4-6-%E6%9C%88-25-%E6%97%A5-%E4%BB%BB%E5%A4%A9%E5%A0%82%E3%82%B9%E3%82%A4%E3%83%83%E3%83%81%E3%81%AE%E3%83%9E%E3%83%AA%E3%82%AA-%E3%83%9E%E3%83%AA%E3%82%AA%E3%82%AB%E3%83%BC%E3%83%88-8-%E3%83%87%E3%83%A9%E3%83%83%E3%82%AF%E3%82%B9%E9%81%8A%E3%81%B6%E7%94%B7.jpg?s=612x612&w=0&k=20&c=TiQrYS2hs9oiMWAvbpl7-kOCh6b_zzYTwcVJ04S7Nzk="],
        owner: "Alex Johnson",
        description: "A popular gaming console for all ages.",
        precaution: "Avoid dropping it.",
        days: 7,
    },
    {
        name: "AirPods Pro",
        status: true,
        price: 200,
        id: "m3n4o5p6",
        photos: ["https://media.istockphoto.com/id/1366646956/ja/%E3%82%B9%E3%83%88%E3%83%83%E3%82%AF%E3%83%95%E3%82%A9%E3%83%88/%E9%BB%92%E3%81%84%E8%83%8C%E6%99%AF%E3%81%ABairpods-3%E4%B8%96%E4%BB%A3.jpg?s=612x612&w=0&k=20&c=zH4hteYpxgoyx82IT5oFHsi2F4dtaeb-TL6ISeYjpLo="],
        owner: "Emily Davis",
        description: "Wireless earbuds with active noise cancellation.",
        precaution: "Keep away from water.",
        days: 3,
    },
    {
        name: "Apple Watch Series 6",
        status: true,
        price: 400,
        id: "q7r8s9t0",
        photos: [],
        owner: "Michael Wilson",
        description: "A smartwatch with health and fitness features.",
        precaution: "Charge regularly.",
        days: 5,
    },
    {
        name: "PlayStation 5",
        status: false,
        price: 500,
        id: "u1v2w3x4",
        photos: [],
        owner: "Sophia Thompson",
        description: "Next-generation gaming console with stunning graphics.",
        precaution: "Handle with care.",
        days: 7,
    },
    {
        name: "Samsung Galaxy S21",
        status: true,
        price: 800,
        id: "y5z6a7b8",
        photos: [],
        owner: "Daniel Martinez",
        description: "A flagship smartphone with a powerful camera.",
        precaution: "Avoid dropping it.",
        days: 7,
    },
    {
        name: "DJI Mavic Air 2",
        status: true,
        price: 1000,
        id: "c9d0e1f2",
        photos: [],
        owner: "Olivia Anderson",
        description: "A compact and powerful drone for aerial photography.",
        precaution: "Fly responsibly and follow local regulations.",
        days: 7,
    },
    {
        name: "GoPro Hero 9",
        status: true,
        price: 300,
        id: "g3h4i5j6",
        photos: [],
        owner: "William Clark",
        description: "A versatile action camera for capturing adventures.",
        precaution: "Handle with care.",
        days: 7,
    },
    {
        name: "Bose QuietComfort 35 II",
        status: true,
        price: 250,
        id: "k7l8m9n0",
        photos: [],
        owner: "Ava Lewis",
        description: "Wireless noise-canceling headphones for immersive audio.",
        precaution: "Avoid exposing to extreme temperatures.",
        days: 7,
    },
    {
        name: "Canon EOS R5",
        status: false,
        price: 3000,
        id: "o1p2q3r4",
        photos: [],
        owner: "James Turner",
        description: "A professional-grade mirrorless camera with high-resolution capabilities.",
        precaution: "Handle with care.",
        days: 7,
    },
    {
        name: "Sony WH-1000XM4",
        status: true,
        price: 350,
        id: "s5t6u7v8",
        photos: [],
        owner: "Sophie Harris",
        description: "Premium wireless headphones with industry-leading noise cancellation.",
        precaution: "Avoid exposing to water.",
        days: 7,
    },
];
