import { ItemProps } from "./components/Item";
import { handlePress, handleLongPress, handleEdit, handleDelete } from "./screens/HomeScreen";

export const dummyItems: ItemProps[] = [
    {
            name: "iPhone 12 Pro",
            status: "Available",
            price: 1000,
            id: "a1b2c3d4",
            photo: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-pro-family-hero?wid=940&hei=1112&fmt=jpeg&qlt=80&.v=1604021662000",
            onPress: (itemID: string) => handlePress(itemID),
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "MacBook Pro",
            status: "Sold",
            price: 2000,
            id: "e5f6g7h8",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Nintendo Switch",
            status: "Rented",
            price: 300,
            id: "i9j0k1l2",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "AirPods Pro",
            status: "Available",
            price: 200,
            id: "m3n4o5p6",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Apple Watch Series 6",
            status: "Sold",
            price: 400,
            id: "q7r8s9t0",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "PlayStation 5",
            status: "Rented",
            price: 500,
            id: "u1v2w3x4",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Samsung Galaxy S21",
            status: "Available",
            price: 800,
            id: "y5z6a7b8",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "DJI Mavic Air 2",
            status: "Sold",
            price: 1000,
            id: "c9d0e1f2",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "GoPro Hero 9",
            status: "Rented",
            price: 300,
            id: "g3h4i5j6",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Bose QuietComfort 35 II",
            status: "Available",
            price: 250,
            id: "k7l8m9n0",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Canon EOS R5",
            status: "Sold",
            price: 3000,
            id: "o1p2q3r4",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
        },
        {
            name: "Sony WH-1000XM4",
            status: "Rented",
            price: 350,
            id: "s5t6u7v8",
            onPress: handlePress,
            onLongPress: handleLongPress,
            onEdit: handleEdit,
            onDelete: handleDelete,
    },
];
