name: Fly Deploy
on:
  push:
    branches:
      - main
    # TODO検証が終わったら戻す
    # paths:
    #   - 'backend/*'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
